# Generated by Django 3.2.18 on 2023-04-06 01:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_like_postings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follwers',
            field=models.ManyToManyField(related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
