# Generated by Django 3.2.18 on 2023-04-06 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_follwers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follwers',
            new_name='followers',
        ),
    ]
